apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap-web-stub.yaml
  - scheduler.yaml
  - executor.yaml
  - python-runtime.yaml
  - api-stub.yaml
  - web-stub.yaml
commonLabels:
  app.kubernetes.io/part-of: scorpio
